### ISSUE TITLE
[L5.2] Class name must be a valid object or a string

### ISSUE THREAD

**Issue by mineass** [Slynova-Org/laravel-commentable#3]
FatalErrorException in Model.php line 852:
Class name must be a valid object or a string

**Comment by RomainLanz** [comment]
Dear for the report @mineass.

Can you give us some code part?

**Comment by mineass** [comment]
i found this error caused by 
`protected $with = ['user'];`

**Comment by RomainLanz** [comment]
Yes, but you will get the same error if you retrieve the user who create the comment.

The problem is there:
```php
public function user()
{
    return $this->belongsTo(config()->get('auth.model'));
}
```

**Comment by Raminsadeghi** [comment]
I have faced to this issue too. Any one can help?

**Comment by RomainLanz** [comment]
@mineass, @Raminsadeghi You can update your version to use the `2.0.0`.

**Comment by Raminsadeghi** [comment]
Thanks a lot.

**Comment by illuminate3** [comment]
This issue still remains.

IF i change to:

```
        return $this->belongsTo('App\Modules\MyUserModule\Http\Models\User');
```

it works.

**Comment by RomainLanz** [comment]
@illuminate3 Which version of Laravel do you use?

5.1 => `1.0.0`
5.2 => `2.0.0`

**Comment by illuminate3** [comment]
I'm on 5.1 so I'll try the 1.0 version. I think I was trying the 2.0 version.

**Comment by himanshu87** [comment]
When comment gets inserted in comments table, it is saving 0 in user_id field.I changed model in auth.php config file to App\Models\User::class as I have my model in this folder app/Models/User.php. But it not saving user_id.

**Comment by RomainLanz** [comment]
@himanshu87 Could you open a new issue please?
