### ISSUE TITLE
Multiple Usage

### ISSUE THREAD

**Issue by illuminate3** [Slynova-Org/laravel-commentable#6]
I was wondering if you"re considering to make this so that you can use it for multiple instances?

I haven't tried to attach this to other category setups that I have in the same app but seeing it only uses a comments table I figured it would break.

**Comment by RomainLanz** [comment]
Hi @illuminate3,

What do you mean? Have you a use case?

**Comment by illuminate3** [comment]
I currently use your package for comments in a ticket system. Baum categories are for the main ticket itself then your package for the comments to the tickets. But let's say that I want to have a FAQ system ... I don't want the comments to be on the same table.

**Comment by RomainLanz** [comment]
Maybe you should create it by yourself.

This package is only a very small wrapper for Baum to manage a commenting system in Laravel.
