### ISSUE TITLE
Extending the Comment Node

### ISSUE THREAD

**Issue by illuminate3** [Slynova-Org/laravel-commentable#7]
What is the best practices for extending the Comment Class?

I'm trying to use a presenter package and Baum keeps throwing errors, If I hard code the presenter into your package it works.

**Comment by RomainLanz** [comment]
Hi @illuminate3,

Which error Baum throw?

**Comment by illuminate3** [comment]
here's my error:
I'm using the laracast presenter package.

```
Call to undefined method Baum\Extensions\Query\Builder::present() (View: 
```

This is the same for Slynova v1.0 and your older Lanz package.

**Comment by RomainLanz** [comment]
Can I see the line of code who throw this exception?
